### PR TITLE
Fix "All shipping methods" bug in "Subscription → Remove Shipping" action

### LINKED ISSUE #45: 'subscription remove shipping' - all shipping methods removes no shipping methods
Reported in #2839811-zen

These actions are configured for a workflow:
see screen shot

The workflow ran, but the shipping was not removed from the subscription.

I tested this locally and the same behavior happens. However, if I specify a shipping method to remove and the subscription has that shipping method, then it does work as expected.

### PR DESCRIPTION
**Pull request by layoutd**
Fixes #45 

Selecting "All shipping methods" in the _Subscription - Remove Shipping_ action didn't actually remove anything from the subscription. The problem was that the workflow was saving the `shipping_method_id` as `all`, and then comparing each individual shipping method in the subscription against that ID (so no single shipping method matched the ID).

I added the condition that removes each shipping method if the ID matches the one provided in the workflow, _or_ if the ID in the workflow is `all`. 

### Detailed test instructions:
- Create a subscription with one or more shipping line items.
- Create a workflow with the action Subscription → Remove Shipping and choose the "All shipping methods" option (recommend trigger Subscriptions → Subscription Note Added).
- Trigger the workflow and confirm that all the shipping methods were properly removed from the subscription.
- Confirm that the "Shipping Method ID" in the note added to the subscription by the workflow isn't `0` (should be something like `flat_rate` or `free_shipping`).

### CODE REVIEW

**Comment by findingsimple** [comment]
@JPry just assigned you this one to get it on your radar

File: includes/abstracts/actions/edit-shipping.php [hunk 1]
```diff
@@ -80,7 +88,7 @@ protected function get_shipping_method_titles() {
 		$shipping_method_titles = [];
 
 		if ( $this->include_all_shipping_method ) {
-			$shipping_method_titles['all'] = __( 'All shipping methods', 'automatewoo-subscriptions' );
+			$shipping_method_titles[$this->all_shipping_method_option_key] = __( 'All shipping methods', 'automatewoo-subscriptions' );
```
Comment (JPry) [inline includes/abstracts/actions/edit-shipping.php]: Minor: This needs spaces around variable in the array access.

```suggestion
			$shipping_method_titles[ $this->all_shipping_method_option_key ] = __( 'All shipping methods', 'automatewoo-subscriptions' );
```

File: includes/actions/remove-shipping.php [hunk 2]
```diff
@@ -62,7 +62,9 @@ protected function edit_subscription( $shipping_data, $subscription ) {
 
 		foreach ( $subscription->get_shipping_methods() as $line_item ) {
 			// Same approach used in Abstract_WC_Order::has_shipping_method() to check for method
-			if ( 0 === strpos( $line_item->get_method_id(), $shipping_data['shipping_method_id'] ) ) {
+			if ( 0 === strpos( $line_item->get_method_id(), $shipping_data['shipping_method_id'] )
```
Comment (JPry) [inline includes/actions/remove-shipping.php]: Minor: If we're going to split the `if` statement across multiple lines, then the first condition should be on its own line.

**Review by JPry — CHANGES_REQUESTED** [review]
Looks good, just some minor formatting issues to address.

**Review by JPry — APPROVED** [review]
LGTM 👍
